apiVersion: batch/v1
kind: Job
metadata:
  name: load-job
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: vegeta
        image: peterevans/vegeta
        #command: ["sh", "-c", "echo 'GET http://mi-service:8290/api1/failover' | vegeta attack -rate=1 -duration=0 -output /dev/null -header 'header1:hi' -header 'header2:bye'"]
        command: ["sh", "-c", "echo 'GET http://mi-service:8290/api1/failoverr' | vegeta attack -rate=1 -duration=0 -output /dev/null -header 'header1:hi' -header 'header2:bye'"]
      restartPolicy: Never
